-- MySQL Script generated by MySQL Workbench
-- Fri Jun 11 10:44:02 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema curso
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `curso` ;

-- -----------------------------------------------------
-- Schema curso
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `curso` DEFAULT CHARACTER SET utf8 ;
USE `curso` ;

-- -----------------------------------------------------
-- Table `curso`.`rol_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curso`.`rol_usuario` (
  `idrol_usuario` INT NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(45) NULL,
  PRIMARY KEY (`idrol_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `curso`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curso`.`usuarios` (
  `idusuarios` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `contra` VARCHAR(45) NULL,
  `sexo` VARCHAR(1) NULL,
  `status` ENUM('activo', 'inactivo') NULL,
  `idrol_usuario` INT NOT NULL,
  PRIMARY KEY (`idusuarios`, `idrol_usuario`),
  INDEX `fk_usuarios_rol_usuario_idx` (`idrol_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_rol_usuario`
    FOREIGN KEY (`idrol_usuario`)
    REFERENCES `curso`.`rol_usuario` (`idrol_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
