-- MySQL Script generated by MySQL Workbench
-- 06/17/21 19:32:36
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema curso1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema curso1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `curso1` DEFAULT CHARACTER SET utf8 ;
USE `curso1` ;

-- -----------------------------------------------------
-- Table `curso1`.`paciente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `curso1`.`paciente` ;

CREATE TABLE IF NOT EXISTS `curso1`.`paciente` (
  `idpaciente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `direccion` VARCHAR(250) NULL,
  `movil` VARCHAR(45) NULL,
  `sexo` CHAR(1) NULL,
  `fech_nac` DATE NULL,
  `documento` VARCHAR(45) NULL,
  `status` ENUM('activo', 'inactivo') NULL,
  PRIMARY KEY (`idpaciente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `curso1`.`historia_clinica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `curso1`.`historia_clinica` ;

CREATE TABLE IF NOT EXISTS `curso1`.`historia_clinica` (
  `idhistoria_clinica` INT NOT NULL AUTO_INCREMENT,
  `fecha_registro` DATE NULL,
  `paciente_idpaciente` INT NOT NULL,
  PRIMARY KEY (`idhistoria_clinica`),
  CONSTRAINT `fk_historia_clinica_paciente1`
    FOREIGN KEY (`paciente_idpaciente`)
    REFERENCES `curso1`.`paciente` (`idpaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `curso1`.`especialidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `curso1`.`especialidad` ;

CREATE TABLE IF NOT EXISTS `curso1`.`especialidad` (
  `idespecialidad` INT NOT NULL AUTO_INCREMENT,
  `especialidad` VARCHAR(45) NULL,
  `fecha_registro` DATE NULL,
  `status` ENUM('activo', 'inactivo') NULL,
  PRIMARY KEY (`idespecialidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `curso1`.`rol_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `curso1`.`rol_usuario` ;

CREATE TABLE IF NOT EXISTS `curso1`.`rol_usuario` (
  `idrol_usuario` INT NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(45) NULL,
  PRIMARY KEY (`idrol_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `curso1`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `curso1`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `curso1`.`usuarios` (
  `idusuarios` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `contra` VARCHAR(45) NULL,
  `sexo` CHAR(1) NULL,
  `status` ENUM('activo', 'inactivo') NULL,
  `email` VARCHAR(45) NULL,
  `idrol_usuario` INT NOT NULL,
  PRIMARY KEY (`idusuarios`),
  CONSTRAINT `fk_usuarios_rol_usuario1`
    FOREIGN KEY (`idrol_usuario`)
    REFERENCES `curso1`.`rol_usuario` (`idrol_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `curso1`.`medico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `curso1`.`medico` ;

CREATE TABLE IF NOT EXISTS `curso1`.`medico` (
  `idmedico` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `movil` VARCHAR(45) NULL,
  `sexo` CHAR(1) NULL,
  `fecha_nac` DATE NULL,
  `documento` VARCHAR(45) NULL,
  `colegiatura` VARCHAR(45) NULL,
  `idespecialidad` INT NOT NULL,
  `idusuarios` INT NOT NULL,
  PRIMARY KEY (`idmedico`),
  CONSTRAINT `fk_medico_especialidad1`
    FOREIGN KEY (`idespecialidad`)
    REFERENCES `curso1`.`especialidad` (`idespecialidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medico_usuario1`
    FOREIGN KEY (`idusuarios`)
    REFERENCES `curso1`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `curso1`.`cita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `curso1`.`cita` ;

CREATE TABLE IF NOT EXISTS `curso1`.`cita` (
  `idcita` INT NOT NULL AUTO_INCREMENT,
  `numero_atencion` INT NULL,
  `fecha_registro` DATETIME NULL,
  `status` ENUM('activo', 'inactivo') NULL,
  `idpaciente` INT NOT NULL,
  `idmedico` INT NOT NULL,
  PRIMARY KEY (`idcita`),
  CONSTRAINT `fk_cita_paciente1`
    FOREIGN KEY (`idpaciente`)
    REFERENCES `curso1`.`paciente` (`idpaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cita_medico1`
    FOREIGN KEY (`idmedico`)
    REFERENCES `curso1`.`medico` (`idmedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `curso1`.`consulta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `curso1`.`consulta` ;

CREATE TABLE IF NOT EXISTS `curso1`.`consulta` (
  `idconsulta` INT NOT NULL AUTO_INCREMENT,
  `descripcion` TEXT(255) NULL,
  `diagnostico` TEXT(255) NULL,
  `fecha_registro` DATE NULL,
  `status` ENUM('activo', 'inactivo') NULL,
  `idcita` INT NOT NULL,
  PRIMARY KEY (`idconsulta`),
  CONSTRAINT `fk_consulta_cita1`
    FOREIGN KEY (`idcita`)
    REFERENCES `curso1`.`cita` (`idcita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `curso1`.`medicamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `curso1`.`medicamentos` ;

CREATE TABLE IF NOT EXISTS `curso1`.`medicamentos` (
  `idmedicamentos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `stock` INT NULL,
  `fecha_registro` DATE NULL,
  `status` ENUM('activo', 'inactivo') NULL,
  PRIMARY KEY (`idmedicamentos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `curso1`.`fua`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `curso1`.`fua` ;

CREATE TABLE IF NOT EXISTS `curso1`.`fua` (
  `idfua` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(12) NULL,
  `fecha_registro` DATE NULL,
  `idhistoria_clinica` INT NOT NULL,
  `idconsulta` INT NOT NULL,
  PRIMARY KEY (`idfua`),
  CONSTRAINT `fk_fua_historia_clinica1`
    FOREIGN KEY (`idhistoria_clinica`)
    REFERENCES `curso1`.`historia_clinica` (`idhistoria_clinica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fua_consulta1`
    FOREIGN KEY (`idconsulta`)
    REFERENCES `curso1`.`consulta` (`idconsulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `curso1`.`detalle_medicamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `curso1`.`detalle_medicamento` ;

CREATE TABLE IF NOT EXISTS `curso1`.`detalle_medicamento` (
  `iddetalle_medicamento` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NULL,
  `idfua` INT NOT NULL,
  `idmedicamentos` INT NOT NULL,
  PRIMARY KEY (`iddetalle_medicamento`),
  CONSTRAINT `fk_detalle_medicamento_fua1`
    FOREIGN KEY (`idfua`)
    REFERENCES `curso1`.`fua` (`idfua`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_medicamento_medicamentos1`
    FOREIGN KEY (`idmedicamentos`)
    REFERENCES `curso1`.`medicamentos` (`idmedicamentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `curso1`.`procedimientos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `curso1`.`procedimientos` ;

CREATE TABLE IF NOT EXISTS `curso1`.`procedimientos` (
  `idprocedimientos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `status` ENUM('activo', 'inactivo') NULL,
  PRIMARY KEY (`idprocedimientos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `curso1`.`detalle_procedimientos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `curso1`.`detalle_procedimientos` ;

CREATE TABLE IF NOT EXISTS `curso1`.`detalle_procedimientos` (
  `iddetalle_procedimientos` INT NOT NULL AUTO_INCREMENT,
  `idprocedimientos` INT NOT NULL,
  `idfua` INT NOT NULL,
  PRIMARY KEY (`iddetalle_procedimientos`),
  CONSTRAINT `fk_detalle_procedimientos_procedimientos1`
    FOREIGN KEY (`idprocedimientos`)
    REFERENCES `curso1`.`procedimientos` (`idprocedimientos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_procedimientos_fua1`
    FOREIGN KEY (`idfua`)
    REFERENCES `curso1`.`fua` (`idfua`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `curso1`.`insumos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `curso1`.`insumos` ;

CREATE TABLE IF NOT EXISTS `curso1`.`insumos` (
  `idinsumos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `stock` INT NULL,
  `fecha_registro` DATE NULL,
  `status` ENUM('activo', 'inactivo') NULL,
  PRIMARY KEY (`idinsumos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `curso1`.`detalle_insumos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `curso1`.`detalle_insumos` ;

CREATE TABLE IF NOT EXISTS `curso1`.`detalle_insumos` (
  `iddetalle_insumos` INT NOT NULL AUTO_INCREMENT,
  `idinsumos` INT NOT NULL,
  `idfua` INT NOT NULL,
  `cantidad` INT NULL,
  PRIMARY KEY (`iddetalle_insumos`),
  CONSTRAINT `fk_detalle_insumos_insumos1`
    FOREIGN KEY (`idinsumos`)
    REFERENCES `curso1`.`insumos` (`idinsumos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_insumos_fua1`
    FOREIGN KEY (`idfua`)
    REFERENCES `curso1`.`fua` (`idfua`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
